version: '3'
services:
    db:
        image: postgres:12.4
        environment:
            POSTGRES_PASSWORD: enviu_dev
            POSTGRES_USER: postgres
        network_mode: host
        #entrypoint: postgres
    blockscout:
        #image: blockscout/blockscout-eth:3.2.1-pre-2
        
        build: 
            context: ..
            dockerfile: docker/Dockerfile
        #volumes:
        #    - ./../:/home/blockscout/src

        # RUN mix do ecto.drop --force, ecto.create, ecto.migrate
        #entrypoint: ["mix", "do", "ecto.create", " ecto.migrate", "phx.server"]

        ports:
            - "4000:4000"
        tty: true
        network_mode: host
        environment:
            ETHEREUM_JSONRPC_HTTP_URL: http://172.17.0.1:8545
            ETHEREUM_JSONRPC_TRACE_URL: http://172.17.0.1:8545
            ETHEREUM_JSONRPC_WS_URL: ws://172.17.0.1:9541
            ETHEREUM_JSONRPC_VARIANT: parity
            HOST: 127.17.0.1
            DATABASE_URL: postgresql://postgres:@127.17.0.1:5432/explorer?ssl=false

